import mongoose from "mongoose";
const Student = mongoose.Schema({
    name:{
        type:String,
        unique:true,
        required:true
    },
    email:{
        type:String,
        unique:true,
        minlength:4,
        default:''
    },
    age:{
        type:Number,
        required:true,
        default:0,
    },
    dob:{
        type:Date,
        required:true,
    },
    totalClassAttended:{
        type:Number,
        default:0
    },
    adhar:{
        type:Number,
        default:0,
    },
    currClass:{
        type:String,
        default:'1st'
    },
    levels:{
        type:String,
        enum:['a','b','c','d'],
        default:'a'
    },
    socioEmotion:{
        type:Number,
        default:0,
        enum:[0,1,2,3,4,5]
    },
    learning:{
        type:Number,
        default:0,
        enum:[0,1,2,3,4,5]
    },
    numeric:{
        type:Number,
        default:0,
        enum:[0,1,2,3,4,5]
    },
    totalClassConducted:{
        type:Number,
        default:0
    },
})
const stuModel = mongoose.model("hackathonstudent",Student);
export default stuModel;